[project]
name = "bldc-modeling"
version = "0.0.1"
description = "A python script to calculate/simulate a BLDC performance from the provided parameters."
authors = [
  { name = "Computed Functions", email = "215638926+computed-fn@users.noreply.github.com" }
]
license = { file = "LICENSE.BSD-3-Clause-Clear" }
requires-python = ">=3.13"
readme = "README.md"
dependencies = []

[tool.neurobot]
